source 'https://rubygems.org'

gem 'opal',           :git => 'git://github.com/opal/opal.git'
gem 'opal-sprockets', :git => 'git://github.com/opal/opal-sprockets.git'
gem 'opal-router',    :path => '..'
